import { Country } from './country';

export const COUNTRIES: Country[] = [
  {
    projectId: '#1258545',
    projectDate: '9/19/2022',
    projectName: 'Website localization from English into French and German',
    type: 'Website',
    name: 'Adham Sabry',
    company: 'P&G',
    accountManager: 'Sarah Lee',
    status: 'Pending Approval',
    cost: '$1,250',
    dueDate: '10/19/2023',
  },
  {
    projectId: '#358285',
    projectDate: '10/2/2023',
    projectName: 'Website localization from English into French and German',
    type: 'Document',
    name: 'Mona Qadry',
    company: 'P&G',
    accountManager: 'Maria Rodriguez',
    status: 'Submitted',
    cost: '$2,391',
    dueDate: '10/19/2023',
  },
  {
    projectId: '#358285',
    projectDate: '10/2/2023',
    projectName: 'Website localization from English into French and German',
    type: 'Software',
    name: 'John Martin',
    company: 'Google',
    accountManager: 'Olivia Nguyen',
    status: 'Submitted',
    cost: '$2,391',
    dueDate: '10/19/2023',
  },
  {
    projectId: '#124545',
    projectDate: '9/19/2022',
    projectName: 'Website localization from English into French and German',
    type: 'Multimedia',
    name: 'Noreldin Mahmoud',
    company: 'P&G',
    accountManager: 'Kim Chang',
    status: 'Canceled',
    cost: '$2,151',
    dueDate: '10/19/2023',
  },
  {
    projectId: '#124545',
    projectDate: '9/19/2022',
    projectName: 'Website localization from English into French and German',
    type: 'Interpretation',
    name: 'Osama Shaaban',
    company: 'P&G',
    accountManager: 'Sarah Lee',
    status: 'Rejected',
    cost: '$2,130',
    dueDate: '10/19/2023',
  },
];
